server:
  port: 80
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/result
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800
spring:
   resources:
     cache:
       period: -1
   profiles.active: dev
   freemarker.cache: false
#  i18n资源文件配置
   messages:
      basename: i18n/base/messages,i18n/main/messages,i18n/sys/messages,i18n/rdb/messages,i18n/mongodb/messages
      encoding: UTF-8
      cache-duration: -1
